### ISSUE TITLE
SERVER_PUBLIC_KEY

### ISSUE THREAD

**Issue by eddywee** [tomquist/solix2mqtt#1]
Hey Tom! 

Danke dir für die Mega vorarbeiten!
Kannst du mir ggf. erklären woher der Server public key kommt? 

Ich versuche das selbe gerade in meinem setup in python and fliegen zu bekommen und habe hier noch so meine probleme.

Gruß und Danke 
Eddy

**Comment by tomquist** [comment]
Der kommt von Eufy: https://github.com/bropat/eufy-security-client/blob/fa8edf478c53499e457fbd68c218f97f0446dfdc/src/http/api.ts#L24

Anker verwendet wohl für den Login den gleichen Mechanismus wie bei ihren Eufy Geräten. Daher konnte ich das weitestgehend übernehmen. Siehe dazu auch [diesen Abschnitt](https://github.com/tomquist/solix2mqtt#auth)  in der README.
