### ISSUE TITLE
Frage zum Setup/Start

### ISSUE THREAD

**Issue by Grothesk242** [tomquist/solix2mqtt#2]
Vermutlich eine blöde Frage, aber ich bekomme das nicht an den Start.

```
echad@chet:/home/iobroker/solix2mqtt/solix2mqtt $ sudo -u iobroker npm run start

> solix2mqtt@1.0.0 start
> node ./bin/app.js

Missing env var S2M_USER
echad@chet:/home/iobroker/solix2mqtt/solix2mqtt $ sudo echo $S2M_USER
meine_email@emailhoster.com
echad@chet:/home/iobroker/solix2mqtt/solix2mqtt $
```

**Comment by Grothesk242** [comment]
Geschnallt... Hab die / überlesen...

**Comment by Grothesk242** [comment]
Ich bekomme das nicht gebeamt... :-( 

``````

**Comment by tomquist** [comment]
Anker erlaubt nur eine bestimmte Anzahl von Logins pro Tag. Wird die überschritten, dann wird der Account für mehrere Stunden (ich glaube es waren 12h) gesperrt. Es sieht so aus als wäre dein Account noch 3h gesperrt.

**Comment by Grothesk242** [comment]
Schon. Aber beim ersten Login-Versuch springt sofort diese Sperre an. War gestern schon für 24 Stunden gesperrt, nach Ablauf der erste Versuch: Bäm, 3 Stunden gesperrt. 
Das Kommando ist aber doch richtig zusammen gesetzt? Nach der Sperre gestern hab ich heute mehrfach Login/Passwort abgeglichen, das passt.

**Comment by Grothesk242** [comment]
Schaut jetzt so aus. Login bei Anker steht, würde ich sagen. Aber jetzt kommt im mosquitto nix an. Andere mqtt-clients liefern aber dort ab, also grundsätzlich funktioniert mqtt hier. Fällt dir dazu noch was ein?
```
> solix2mqtt@1.0.0 start
> node ./bin/app.js

[2023-10-20T22:30:12.781Z] {"username":"email@gmail.com","password":"***","country":"DE","loginStore":"auth.data","pollInterval":30,"mqttUrl":"host.fritz.box:1883","mqttClientId":"solix2mqtt","mqttUsername":"user","mqttPassword":"p4Ssw0rd","mqttRetain":false,"mqttTopic":"solix","verbose":true}
[2023-10-20T22:30:12.788Z] Fetching data
[2023-10-20T22:30:12.794Z] Using cached auth data
[2023-10-20T22:30:12.794Z] 65----------------------------60
[2023-10-20T22:30:12.796Z] {}
```

**Comment by Grothesk242** [comment]
Hab es hinbekommen. Es fehlten "" um den mqtt-Login. -_-

**Comment by Grothesk242** [comment]
Closed.
