### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by lowrisk75** [tomquist/solix2mqtt#5]
Sorry in advance, but I can't manage to found anker API?

I need it for the following info 
S2M_USER (required): A Solix API client id
S2M_PASSWORD (required): The client secret

I created a debian LXC , I installed nodeJS and did  update but then I don't know how to continue since I can't the API...
Thinking about it I always used API published by companies's dev website, but maybe I got that wrong here?

**Comment by tomquist** [comment]
Ah sorry, I never noticed that the description of these values is wrong. It’s actually your username & password you use for logging into the the app.

**Comment by lowrisk75** [comment]
Thank you!
