### ISSUE TITLE
Only empty data

### ISSUE THREAD

**Issue by mkeller0815** [tomquist/solix2mqtt#8]
I have the docker image running with all parameters set. The connect and the polling seems to work, but the only message I can see in my MQTT broker is solix/site_homepage with some empty arrays. 

I tested with the Anker Solix python library with the same credentials to see if I get data from the Anker API and I do get all details there. 
So it does not seem to be the Anker side. If I set S2M_VERBOSE to true I don't see any data that is polled, but I'm not sure if it should be shown there. Is there a way to debug if the client does not get any data or the MQTT publish does not work correctly.

**Comment by mkeller0815** [comment]
Okay, I can confirm that the data is shown if I use the main account for the credentlals. So with unsing an account that has the resources only shared, the code needs to be changed.

**Comment by tomquist** [comment]
I don’t own an Anker Solix anymore so I won’t be able to fix the issue by myself. Would appreciate a PR though.

**Comment by mkeller0815** [comment]
Unfortunately I don't have any experience with Typescript, so I'm not able to fix this. I could provide access to a readonly account for testing if that helps.

**Comment by oemich** [comment]
I created a pull request which enables the usage of "Shared Accounts". This removes the limitation to decide whether to use the App or the "solix2mqtt" service.

**Comment by mkeller0815** [comment]
Cool, thanks for the support.
